services:
  exclusive-shop-ai:
    build: .
    container_name: exclusive-shop-ai

    ports:
      - "8000:8000"

    env_file:
      - .env

    volumes:
      - ./data:/app/data

    restart: unless-stopped