FAQ_PATTERNS = {

    "tienda": [
        "tienda fisica",
        "tienda física",
        "local",
        "donde estan",
        "dónde están",
        "donde queda",
        "dónde queda",
        "direccion",
        "dirección",
        "oficina",
    ],

    "envio": [
        "envio",
        "envío",
        "costo de envio",
        "costo de envío",
        "cuanto cuesta el envio",
        "cuánto cuesta el envío",
        "hacen envios",
        "hacen envíos",
        "envian",
        "envían",
        "delivery",
        "provincia",
        "provincias",
        "envio a provincia",
        "envío a provincia",
    ],

    "tiempo_entrega": [
        "cuanto demora",
        "cuánto demora",
        "cuanto tarda",
        "cuánto tarda",
        "tiempo de entrega",
        "dias habiles",
        "días hábiles",
        "cuando llega",
        "cuándo llega",
        "cuanto tiempo",
        "cuánto tiempo",
        "demora",
        "tarda",
        "llega",
    ],

    "pagos": [
        "metodo de pago",
        "método de pago",
        "metodos de pago",
        "métodos de pago",
        "opcion de pago",
        "opción de pago",
        "opciones de pago",
        "forma de pago",
        "formas de pago",
        "como puedo pagar",
        "cómo puedo pagar",
        "aceptan tarjeta",
        "tarjeta",
        "plin",
        "transferencia",
        "deposito",
        "depósito",
    ],

    "marcas": [
        "marca",
        "marcas",
        "que marcas",
        "qué marcas",
        "que marcas manejan",
        "qué marcas manejan",
        "que marcas venden",
        "qué marcas venden",
        "que marcas tienen",
        "qué marcas tienen",
        "marcas manejan",
        "marcas venden",
        "marcas tienen",
        "con que marcas trabajan",
        "con qué marcas trabajan",
        "trabajan con marcas",
    ],

    "confianza": [
        "es confiable",
        "son confiables",
        "es seguro",
        "son seguros",
        "me van a estafar",
        "me estafaran",
        "me estafarán",
        "es original",
        "son originales",
        "originales",
        "garantia",
        "garantía",
    ],

    "categorias": [
        "que categorias",
        "qué categorías",
        "categorias",
        "categorías",
        "que categorias tienen",
        "qué categorías tienen",
        "que venden",
        "qué venden",
        "que productos venden",
        "qué productos venden",
        "que productos tienen",
        "qué productos tienen",
        "que tipo de productos venden",
        "qué tipo de productos venden",
        "productos manejan",
        "productos tienen",
    ],

}
